version: '3.9'

volumes:
  educational_program_db:

services:

  educational_program_service:
    container_name: educational_program_service
    image: educational_program_service
    depends_on:
      - educational_program_db
    build:
      context: ./schedule-educational-program-service
      dockerfile: ./deployments/Dockerfile
    ports:
      - '4000:8080'
      - '5000:9090'
    environment:
      - POSTGRESQL_HOST=host.docker.internal
      - POSTGRESQL_PORT=6000
      - POSTGRESQL_USER=educational_program
      - POSTGRESQL_PASSWORD=P@ssw0rd
      - POSTGRESQL_DATABASE=educational_program
      - HTTP_HOST=localhost
      - HTTP_PORT=8080
      - GRPC_HOST=localhost
      - GRPC_PORT=9090

  educational_program_db:
    container_name: educational_program_db
    image: postgres:latest
    build:
      context: ./schedule-educational-program-service
    ports:
      - '6000:5432'
    environment:
      - POSTGRES_DB=educational_program
      - POSTGRES_USER=educational_program
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_PORT=5432
    volumes:
      - educational_program_db:/var/lib/postgresql/data