version: '3.9'

services:

  database:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/sqldata
      - sqllog:/var/opt/sqlserver/sqllog
      - sqlbackup:/var/opt/sqlserver/sqlbackups

  api:
    container_name: Api
    image: api
    build:
      context: ./Schedule
      dockerfile: Schedule.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - database
    restart: always
  
  react:
    container_name: React
    image: react
    build: ./schedule-react-app
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: