# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  api:
    build:
      context: "/Users/svetlov/RiderProjects/Schedule/Schedule"
      dockerfile: "Schedule.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Schedule.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "/Users/svetlov/.nuget/packages:/root/.nuget/packages"
    - "/Users/svetlov/RiderProjects/Schedule/Schedule/Schedule.Api:/app:rw"
    - "/Users/svetlov/RiderProjects/Schedule/Schedule:/src:rw"
    working_dir: "/app"
