# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  api:
    build:
      context: "/Users/ivansvetlov/RiderProjects/Schedule/Schedule"
      dockerfile: "Schedule.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Schedule.Api.dll"
    environment: {}
    image: "api:dev"
    ports: []
    volumes:
    - "/Users/ivansvetlov/RiderProjects/Schedule/Schedule/Schedule.Api:/app:rw"
    working_dir: "/app"
