export enum ApiTags {
    Classroom = 'Classroom',
    ClassroomType = 'ClassroomType',
    Course = 'Course',
    Date = 'Date',
    Day = 'Day',
    Discipline = 'Discipline',
    DisciplineType = 'DisciplineType',
    Group = 'Group',
    Lesson = 'Lesson',
    LessonNumber = 'LessonNumber',
    LessonTemplate = 'LessonTemplate',
    Role = 'Role',
    Speciality = 'Speciality',
    Teacher = 'Teacher',
    Template = 'Template',
    Term = 'Term',
    Time = 'Time',
    Timetable = 'Timetable',
    TimeType = 'TimeType',
    User = 'User',
    WeekType = 'WeekType',
}