using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Schedule.Core.Models;

namespace Schedule.Persistence.Configurations;

public sealed class DisciplineNameEntityTypeConfiguration : IEntityTypeConfiguration<DisciplineName>
{
    public void Configure(EntityTypeBuilder<DisciplineName> builder)
    {
        builder.HasIndex(e => e.Name, "IX_DisciplineNames").IsUnique();
        builder.Property(e => e.Name).HasMaxLength(50);
        builder.HasData(new DisciplineName[]
        {
            new() { DisciplineNameId = 1, Name = "ААС", IsDeleted = false, },
            new() { DisciplineNameId = 2, Name = "БЖД", IsDeleted = false, },
            new() { DisciplineNameId = 3, Name = "БИОЛОГИЯ", IsDeleted = false, },
            new() { DisciplineNameId = 4, Name = "ВТ", IsDeleted = false, },
            new() { DisciplineNameId = 5, Name = "ГЕОГРАФИЯ", IsDeleted = false, },
            new() { DisciplineNameId = 6, Name = "ДМ", IsDeleted = false, },
            new() { DisciplineNameId = 7, Name = "ДМ С ЭМЛ", IsDeleted = false, },
            new() { DisciplineNameId = 8, Name = "И И КГ", IsDeleted = false, },
            new() { DisciplineNameId = 9, Name = "ИБ", IsDeleted = false, },
            new() { DisciplineNameId = 11, Name = "ИКГ", IsDeleted = false, },
            new() { DisciplineNameId = 12, Name = "ИНДИВИДУАЛЬНЫЙ ПРОЕКТ", IsDeleted = false, },
            new() { DisciplineNameId = 13, Name = "ИНЖЕНЕРНАЯ ГРАФИКА", IsDeleted = false, },
            new() { DisciplineNameId = 14, Name = "ИНОСТРАННЫЙ ЯЗЫК", IsDeleted = false, },
            new() { DisciplineNameId = 15, Name = "ИНОСТРАННЫЙ ЯЗЫК В ПД", IsDeleted = false, },
            new() { DisciplineNameId = 16, Name = "ИНФОРМАТИКА", IsDeleted = false, },
            new() { DisciplineNameId = 17, Name = "ИП", IsDeleted = false, },
            new() { DisciplineNameId = 18, Name = "ИСТОРИЯ", IsDeleted = false, },
            new() { DisciplineNameId = 19, Name = "ИСТОРИЯ РОССИИ", IsDeleted = false, },
            new() { DisciplineNameId = 20, Name = "ИТ", IsDeleted = false, },
            new() { DisciplineNameId = 21, Name = "КМ", IsDeleted = false, },
            new() { DisciplineNameId = 22, Name = "КС", IsDeleted = false, },
            new() { DisciplineNameId = 23, Name = "ЛИТЕРАТУРА", IsDeleted = false, },
            new() { DisciplineNameId = 24, Name = "МАТЕМАТИКА", IsDeleted = false, },
            new() { DisciplineNameId = 25, Name = "МДК.01.01", IsDeleted = false, },
            new() { DisciplineNameId = 26, Name = "МДК.01.02", IsDeleted = false, },
            new() { DisciplineNameId = 27, Name = "МДК.01.03", IsDeleted = false, },
            new() { DisciplineNameId = 28, Name = "МДК.01.04", IsDeleted = false, },
            new() { DisciplineNameId = 29, Name = "МДК.01.05", IsDeleted = false, },
            new() { DisciplineNameId = 30, Name = "МДК.02.01", IsDeleted = false, },
            new() { DisciplineNameId = 31, Name = "МДК.02.02", IsDeleted = false, },
            new() { DisciplineNameId = 32, Name = "МДК.02.03", IsDeleted = false, },
            new() { DisciplineNameId = 33, Name = "МДК.03.01", IsDeleted = false, },
            new() { DisciplineNameId = 34, Name = "МДК.03.02", IsDeleted = false, },
            new() { DisciplineNameId = 35, Name = "МДК.03.03", IsDeleted = false, },
            new() { DisciplineNameId = 36, Name = "МДК.03.04", IsDeleted = false, },
            new() { DisciplineNameId = 37, Name = "МДК.03.05", IsDeleted = false, },
            new() { DisciplineNameId = 38, Name = "МДК.04.01", IsDeleted = false, },
            new() { DisciplineNameId = 39, Name = "МДК.04.02", IsDeleted = false, },
            new() { DisciplineNameId = 40, Name = "МДК.05.01", IsDeleted = false, },
            new() { DisciplineNameId = 41, Name = "МДК.05.02", IsDeleted = false, },
            new() { DisciplineNameId = 42, Name = "МДК.05.03", IsDeleted = false, },
            new() { DisciplineNameId = 43, Name = "МДК.06.01", IsDeleted = false, },
            new() { DisciplineNameId = 44, Name = "МДК.08.01", IsDeleted = false, },
            new() { DisciplineNameId = 45, Name = "МДК.08.02", IsDeleted = false, },
            new() { DisciplineNameId = 46, Name = "МДК.09.01", IsDeleted = false, },
            new() { DisciplineNameId = 47, Name = "МДК.09.02", IsDeleted = false, },
            new() { DisciplineNameId = 48, Name = "МДК.09.03", IsDeleted = false, },
            new() { DisciplineNameId = 49, Name = "МДК.11.01", IsDeleted = false, },
            new() { DisciplineNameId = 50, Name = "МЕНЕДЖМЕНТ", IsDeleted = false, },
            new() { DisciplineNameId = 51, Name = "МЕНЕДЖМЕНТ В ПД", IsDeleted = false, },
            new() { DisciplineNameId = 53, Name = "МС И С", IsDeleted = false, },
            new() { DisciplineNameId = 54, Name = "О И ПОИБ", IsDeleted = false, },
            new() { DisciplineNameId = 55, Name = "ОА И П", IsDeleted = false, },
            new() { DisciplineNameId = 56, Name = "ОБЖ", IsDeleted = false, },
            new() { DisciplineNameId = 57, Name = "ОБП", IsDeleted = false, },
            new() { DisciplineNameId = 58, Name = "ОБЩЕСТВОЗНАНИЕ", IsDeleted = false, },
            new() { DisciplineNameId = 59, Name = "ОИБ", IsDeleted = false, },
            new() { DisciplineNameId = 60, Name = "ОПБД", IsDeleted = false, },
            new() { DisciplineNameId = 61, Name = "ОС И С", IsDeleted = false, },
            new() { DisciplineNameId = 62, Name = "ОСНОВЫ БЕРЕЖЛИВОГО ПРОИЗВОДСТВА", IsDeleted = false, },
            new() { DisciplineNameId = 63, Name = "ОСНОВЫ ФИЛОСОФИИ", IsDeleted = false, },
            new() { DisciplineNameId = 64, Name = "ОСНОВЫ ФИНАНСОВОЙ ГРАМОТНОСТИ", IsDeleted = false, },
            new() { DisciplineNameId = 65, Name = "ОСНОВЫ ЭТ", IsDeleted = false, },
            new() { DisciplineNameId = 66, Name = "ОСНОВЫ ЭТХ", IsDeleted = false, },
            new() { DisciplineNameId = 67, Name = "ОТИ", IsDeleted = false, },
            new() { DisciplineNameId = 68, Name = "ОТК", IsDeleted = false, },
            new() { DisciplineNameId = 69, Name = "ОФГ", IsDeleted = false, },
            new() { DisciplineNameId = 70, Name = "ОЭ И ВТ", IsDeleted = false, },
            new() { DisciplineNameId = 71, Name = "ОЭТХ", IsDeleted = false, },
            new() { DisciplineNameId = 73, Name = "ПОКС И WEB-СЕРВЕРОВ", IsDeleted = false, },
            new() { DisciplineNameId = 74, Name = "ПОПД", IsDeleted = false, },
            new() { DisciplineNameId = 75, Name = "ПП", IsDeleted = false, },
            new() { DisciplineNameId = 76, Name = "ПП.01", IsDeleted = false, },
            new() { DisciplineNameId = 77, Name = "ПП.02", IsDeleted = false, },
            new() { DisciplineNameId = 78, Name = "ПП.03", IsDeleted = false, },
            new() { DisciplineNameId = 79, Name = "ПП.04", IsDeleted = false, },
            new() { DisciplineNameId = 80, Name = "ПП.05", IsDeleted = false, },
            new() { DisciplineNameId = 81, Name = "ПП.06", IsDeleted = false, },
            new() { DisciplineNameId = 82, Name = "ПП.08", IsDeleted = false, },
            new() { DisciplineNameId = 83, Name = "ПП.09", IsDeleted = false, },
            new() { DisciplineNameId = 84, Name = "ПП.11", IsDeleted = false, },
            new() { DisciplineNameId = 85, Name = "ППОПД", IsDeleted = false, },
            new() { DisciplineNameId = 86, Name = "ПРИКЛАДНАЯ ЭЛЕКТРОНИКА", IsDeleted = false, },
            new() { DisciplineNameId = 87, Name = "ПСИХОЛОГИЯ ОБЩЕНИЯ", IsDeleted = false, },
            new() { DisciplineNameId = 88, Name = "РУССКИЙ ЯЗЫК", IsDeleted = false, },
            new() { DisciplineNameId = 89, Name = "РЯ И КР", IsDeleted = false, },
            new() { DisciplineNameId = 90, Name = "СС И ТД", IsDeleted = false, },
            new() { DisciplineNameId = 91, Name = "ТВИМС", IsDeleted = false, },
            new() { DisciplineNameId = 92, Name = "ТФУПД", IsDeleted = false, },
            new() { DisciplineNameId = 93, Name = "ТЭС", IsDeleted = false, },
            new() { DisciplineNameId = 94, Name = "ТЭЦ", IsDeleted = false, },
            new() { DisciplineNameId = 95, Name = "УП.01", IsDeleted = false, },
            new() { DisciplineNameId = 96, Name = "УП.02", IsDeleted = false, },
            new() { DisciplineNameId = 97, Name = "УП.03", IsDeleted = false, },
            new() { DisciplineNameId = 98, Name = "УП.04", IsDeleted = false, },
            new() { DisciplineNameId = 99, Name = "УП.05", IsDeleted = false, },
            new() { DisciplineNameId = 100, Name = "УП.06", IsDeleted = false, },
            new() { DisciplineNameId = 101, Name = "УП.08", IsDeleted = false, },
            new() { DisciplineNameId = 102, Name = "УП.09", IsDeleted = false, },
            new() { DisciplineNameId = 103, Name = "УП.11", IsDeleted = false, },
            new() { DisciplineNameId = 104, Name = "ФИЗИКА", IsDeleted = false, },
            new() { DisciplineNameId = 105, Name = "ФИЗИЧЕСКАЯ КУЛЬТУРА", IsDeleted = false, },
            new() { DisciplineNameId = 107, Name = "ХИМИЯ", IsDeleted = false, },
            new() { DisciplineNameId = 108, Name = "ЧИСЛЕННЫЕ МЕТОДЫ", IsDeleted = false, },
            new() { DisciplineNameId = 109, Name = "Э И СХТ", IsDeleted = false, },
            new() { DisciplineNameId = 110, Name = "ЭВМ", IsDeleted = false, },
            new() { DisciplineNameId = 111, Name = "ЭКОНОМИКА И УПРАВЛЕНИЕ", IsDeleted = false, },
            new() { DisciplineNameId = 112, Name = "ЭКОНОМИКА ОТРАСЛИ", IsDeleted = false, },
            new() { DisciplineNameId = 113, Name = "ЭЛЕКТРОННАЯ ТЕХНИКА", IsDeleted = false, },
            new() { DisciplineNameId = 114, Name = "ЭЛЕКТРОТЕХНИКА", IsDeleted = false, },
            new() { DisciplineNameId = 115, Name = "ЭРИ", IsDeleted = false, },
            new() { DisciplineNameId = 116, Name = "ЭТ", IsDeleted = false, },
            new() { DisciplineNameId = 117, Name = "ЭТИ", IsDeleted = false, },
            new() { DisciplineNameId = 118, Name = "ЭТС", IsDeleted = false, },
        });
    }
}